export const AMENITY_NAMES = [
  "wifi",
  "kitchen",
  "free_parking",
  "air_conditioning",
  "heating",
  "washer",
  "dryer",
  "pool",
  "hot_tub",
  "gym",
  "tv",
  "dedicated_workspace",
  "self_check_in",
  "crib",
  "ev_charger",
  "indoor_fireplace",
  "breakfast",
  "smoking_allowed",
  "bbq_grill",
  "hair_dryer",
  "iron",
  "smoke_alarm",
  "carbon_monoxide_alarm",
  "king_bed",
] as const;